# -*- coding: utf-8 -*-

Import('*')

pdfOutputSlides = texEnv.PDF('slides.tex')
Depends(pdfOutputSlides, [Glob('img/*.pdf'), Glob('sections/*.tex')])
texEnv.Clean(pdfOutputSlides, 'slides.synctex.gz')

Return('pdfOutputSlides')

# vim: set filetype=python
